# Prod environment overrides for secret-store chart.

secretStore:
  name: secret-store
  region: ap-southeast-7

serviceAccount:
  name: eks-secret-store-irsa
  irsaRoleArn: "arn:aws:iam::<PROD_ACCOUNT_ID>:role/<PROD_ROLE_NAME>"

externalSecret:
  name: app-secrets   # must match secretName in app values-prod.yaml
  key: "prod/app"     # AWS Secrets Manager secret name
